name: Deploy to Dev (Amazon S3)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Run commands
      run: |
        aws s3 sync ./src/ s3://demo-app-dev.cloudcontract.jp --exact-timestamps --delete
        aws s3 cp ./src/v0/js/et-account-dev.js s3://demo-app-dev.cloudcontract.jp/v0/js/et-account.js
        aws s3 cp ./src/v0/apiGateway-js-sdk/apigClient-dev.js s3://demo-app-dev.cloudcontract.jp/v0/apiGateway-js-sdk/apigClient.js
        aws s3 rm s3://demo-app-dev.cloudcontract.jp/v0/js/et-account-dev.js
        aws s3 rm s3://demo-app-dev.cloudcontract.jp/v0/js/et-account-prod.js
        aws s3 rm s3://demo-app-dev.cloudcontract.jp/v0/apiGateway-js-sdk/apigClient-dev.js
        aws s3 rm s3://demo-app-dev.cloudcontract.jp/v0/apiGateway-js-sdk/apigClient-prod.js
